# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "bookshelf-apps" ]
  pull_request:
    branches: [ "bookshelf-apps" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
    - run: |
        git fetch --prune --unshallow      
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - name: Deploy to heroku
      env:
        HEROKU_DEPLOY_SECRET: ${{secrets.HEROKU_DEPLOY_SECRET}}
        HEROKU_APP_NAME: ${{secrets.HEROKU_APP_NAME}}
      if: github.ref == 'refs/heads/bookshelf-apps' && job.status == 'success'
      run: |
        git remote add heroku https://heroku:$HEROKU_DEPLOY_SECRET@git.heroku.com/$HEROKU_APP_NAME.git
        git push heroku HEAD:master -f    
